### ISSUE TITLE
Information text not formatted 

### ISSUE THREAD

**Issue by RachidLeLaborantin** [rhwood/jinputvalidator#92]
It became a problem when the string used as information about the Validation Type become more big. It takes along the lines but I want to wrap at somes part of string.
I tried HTML format string and Text Alignment, it doesn't work

And I also want to ask if there is no a library as yours but for android developers, I like it and I want to use it for android app

**Comment by rhwood** [comment]
@RachidLeLaborantin Are you using full HTML in your Strings, or HTML formatting without the `<HTML></HTML>` tags?

**Comment by rhwood** [comment]
> @RachidLeLaborantin Are you using full HTML in your Strings, or HTML formatting without the `<HTML></HTML>` tags?

Per [this Stackoverflow answer](https://stackoverflow.com/questions/5915061/html-in-jtextarea-of-jeditorpane-jtextpane) JTextField, and JTextArea do not support rendering HTML in Strings. Which component are you attempting to use?

**Comment by rhwood** [comment]
No response from OP.
